# Stolen shamelessly then adapted from https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml
# The way this works is the following:
#
# The create-release job runs purely to initialize the GitHub release itself
# and to output upload_url for the following job.
#
# The build-release job runs only once create-release is finished. It gets the
# release upload URL from create-release job outputs, then builds the release
# executables for each supported platform and attaches them as release assets
# to the previously created release.
#
# The key here is that we create the release only once.
#
# Reference:
# https://eugene-babichenko.github.io/blog/2020/05/09/github-actions-cross-platform-auto-releases/

name: release
on:
  push:
    # Enable when testing release infrastructure on a branch.
    # branches:
    # - ag/work
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    
  
jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-22.04
    # env:
      # Set to force version number, e.g., when no tag exists.
      # RG_VERSION: TEST-0.0.0
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      version: ${{ env.VERSION }}
    steps:
      - name: Get the release version from the tag
        shell: bash
        if: env.VERSION == ''
        run: |
          # Apparently, this is the right way to get a tag name. Really?
          #
          # See: https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32167/highlight/true#M1027
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "version is: ${{ env.VERSION }}"
      - name: Create GitHub release
        id: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}

  build-release:
    name: build-release
    needs: ['create-release']
    runs-on: ${{ matrix.os }}
    env:
      # For some builds, we use cross to test on 32-bit and big-endian
      # systems.
      CARGO: cargo
      # When CARGO is set to CROSS, this is set to `--target matrix.target`.
      TARGET_FLAGS: ""
      # When CARGO is set to CROSS, TARGET_DIR includes matrix.target.
      TARGET_DIR: ./target
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        build: [linux, linux-aarch64, linux-arm, macos, macos-aarch64]
        include:
        - build: linux
          os: ubuntu-24.04
          rust: nightly
          target: x86_64-unknown-linux-musl
        - build: linux-aarch64
          os: ubuntu-24.04
          rust: nightly
          target: aarch64-unknown-linux-musl
        - build: linux-arm
          os: ubuntu-24.04
          rust: nightly
          target: arm-unknown-linux-gnueabihf
        - build: macos
          os: macos-13
          rust: nightly
          target: x86_64-apple-darwin
        - build: macos-aarch64
          os: macos-latest
          rust: nightly
          target: aarch64-apple-darwin

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install packages (Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      run: sudo apt-get install -y --no-install-recommends musl-tools

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}

    - name: Use Cross
      if: matrix.os != 'macos-13' && matrix.os != 'macos-latest'
      shell: bash
      run: |
        cargo install cross
        echo "CARGO=cross" >> $GITHUB_ENV
        echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
        echo "TARGET_DIR=./target/${{ matrix.target }}" >> $GITHUB_ENV

    - name: Show command used for Cargo
      run: |
        echo "cargo command is: ${{ env.CARGO }}"
        echo "target flag is: ${{ env.TARGET_FLAGS }}"
        echo "target dir is: ${{ env.TARGET_DIR }}"

    - name: Build release binary (mcfly-fzf)
      run: ${{ env.CARGO }} build --verbose --release ${{ env.TARGET_FLAGS }}
    
    - name: Build release binary (mcfly)
      run: ${{ env.CARGO }} build --verbose --release ${{ env.TARGET_FLAGS }} -p mcfly

    - name: Build archive
      shell: bash
      run: |
        tar -czvf mcfly-fzf.tar.gz --directory=${{ env.TARGET_DIR }}/release mcfly mcfly-fzf
        echo "ASSET=mcfly-fzf.tar.gz" >> $GITHUB_ENV

    - name: Upload release archive
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ${{ env.ASSET }}
        asset_name: mcfly-fzf-${{ needs.create-release.outputs.version }}-${{ matrix.target }}.tar.gz
        asset_content_type: application/gzip
